import { defineConfig } from "oxlint";

export default defineConfig({
  plugins: ["typescript"],
  categories: {
    correctness: "warn",
  },
  rules: {
    "eslint/no-unused-vars": "error",
  },
  ignorePatterns: [
    "**/dist/**",
    "**/build/**",
    "**/.adonisjs/**",
    "**/.nuxt/**",
    "**/node_modules/**",
    "**/*.d.ts",
    "**/public/assets/**",
  ],
  overrides: [
    {
      files: ["apps/api/**/*.ts"],
      plugins: ["typescript", "unicorn", "node"],
      env: { node: true },
      rules: {
        curly: ["error", "all"],
        eqeqeq: ["error", "always"],
        "no-array-constructor": "error",
        "no-caller": "error",
        "no-cond-assign": ["error", "except-parens"],
        "no-constant-condition": "error",
        "no-control-regex": "error",
        "no-debugger": "error",
        "no-duplicate-case": "error",
        "no-eval": "error",
        "no-ex-assign": "error",
        "no-extra-boolean-cast": "error",
        "no-fallthrough": "error",
        "no-inner-declarations": "error",
        "no-invalid-regexp": "error",
        "no-irregular-whitespace": "error",
        "no-new-wrappers": "error",
        "no-proto": "error",
        "no-regex-spaces": "error",
        "no-self-assign": "error",
        "no-self-compare": "error",
        "no-shadow": "error",
        "no-sparse-arrays": "error",
        "no-this-before-super": "error",
        "no-undef-init": "error",
        "no-unreachable": "error",
        "no-unsafe-finally": "error",
        "no-unsafe-negation": "error",
        "no-with": "error",
        "one-var": ["error", "never"],
        "use-isnan": "error",
        "valid-typeof": "error",
        "no-unused-vars": "error",
        "node/handle-callback-err": ["error", "^(err|error)$"],
        "typescript/consistent-type-imports": [
          "error",
          { fixStyle: "inline-type-imports", disallowTypeAnnotations: false },
        ],
        "typescript/no-shadow": "error",
        "unicorn/prefer-module": "error",
        "unicorn/prefer-node-protocol": "error",
        "unicorn/filename-case": ["error", { case: "snakeCase" }],
        "unicorn/no-await-expression-member": "error",
        "unicorn/no-for-loop": "error",
        "unicorn/prefer-number-properties": "error",
      },
    },
    {
      files: ["apps/web/**/*.{ts,vue}"],
      plugins: ["typescript", "vue"],
      env: { browser: true, es2022: true },
      rules: {
        "typescript/consistent-type-imports": [
          "error",
          { fixStyle: "inline-type-imports", disallowTypeAnnotations: false },
        ],
        "vue/no-unused-vars": "error",
        "vue/no-template-shadow": "error",
        "vue/no-dupe-keys": "error",
        "vue/no-parsing-error": "error",
      },
    },
  ],
});
