/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Auth: () => import("#controllers/auth_controller"),
  Preferences: () => import("#controllers/preferences_controller"),
  Project: () => import("#controllers/project_controller"),
};
