/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from "@adonisjs/lucid/orm";
import { DateTime } from "luxon";

export class ContributorSchema extends BaseModel {
  static $columns = [
    "avatarUrl",
    "contributions",
    "createdAt",
    "githubUserId",
    "id",
    "login",
    "profileUrl",
    "projectId",
    "updatedAt",
  ] as const;
  $columns = ContributorSchema.$columns;
  @column()
  declare avatarUrl: string;
  @column()
  declare contributions: number | null;
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null;
  @column()
  declare githubUserId: bigint | number | null;
  @column({ isPrimary: true })
  declare id: string;
  @column()
  declare login: string;
  @column()
  declare profileUrl: string;
  @column()
  declare projectId: string | null;
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null;
}

export class GithubFetchCacheSchema extends BaseModel {
  static $columns = [
    "createdAt",
    "difficulty",
    "fetchedAt",
    "id",
    "language",
    "totalStored",
    "updatedAt",
  ] as const;
  $columns = GithubFetchCacheSchema.$columns;
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null;
  @column()
  declare difficulty: string;
  @column.dateTime()
  declare fetchedAt: DateTime;
  @column({ isPrimary: true })
  declare id: string;
  @column()
  declare language: string;
  @column()
  declare totalStored: number;
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null;
}

export class ProjectSchema extends BaseModel {
  static $columns = [
    "createdAt",
    "description",
    "detailsFetchedAt",
    "difficulty",
    "forksCount",
    "githubRepoId",
    "id",
    "language",
    "languages",
    "latestRelease",
    "name",
    "openIssuesCount",
    "ownerName",
    "readme",
    "repositoryUrl",
    "stars",
    "topics",
    "totalContributorsCount",
    "updatedAt",
  ] as const;
  $columns = ProjectSchema.$columns;
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null;
  @column()
  declare description: string | null;
  @column.dateTime()
  declare detailsFetchedAt: DateTime | null;
  @column()
  declare difficulty: string;
  @column()
  declare forksCount: number;
  @column()
  declare githubRepoId: bigint | number;
  @column({ isPrimary: true })
  declare id: string;
  @column()
  declare language: string | null;
  @column()
  declare languages: any | null;
  @column()
  declare latestRelease: string | null;
  @column()
  declare name: string;
  @column()
  declare openIssuesCount: number;
  @column()
  declare ownerName: string;
  @column()
  declare readme: string | null;
  @column()
  declare repositoryUrl: string;
  @column()
  declare stars: number;
  @column()
  declare topics: any | null;
  @column()
  declare totalContributorsCount: number | null;
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null;
}

export class UserProjectFavoriteSchema extends BaseModel {
  static $columns = ["createdAt", "id", "projectId", "updatedAt", "userId"] as const;
  $columns = UserProjectFavoriteSchema.$columns;
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null;
  @column({ isPrimary: true })
  declare id: string;
  @column()
  declare projectId: string;
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null;
  @column()
  declare userId: string;
}

export class UserSchema extends BaseModel {
  static $columns = [
    "avatarUrl",
    "createdAt",
    "email",
    "githubAccessToken",
    "id",
    "isVerified",
    "name",
    "preferences",
    "updatedAt",
  ] as const;
  $columns = UserSchema.$columns;
  @column()
  declare avatarUrl: string | null;
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null;
  @column()
  declare email: string;
  @column()
  declare githubAccessToken: string | null;
  @column({ isPrimary: true })
  declare id: string;
  @column()
  declare isVerified: boolean | null;
  @column()
  declare name: string | null;
  @column()
  declare preferences: any | null;
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null;
}
